language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt"
before_script:
    - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.13.zip
    - unzip -q google_appengine_1.9.13.zip
script:
    - make secret_passphrase
    - make unit_test
    - coverage combine
after_success:
    coveralls
