language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt"
    - "(cd mind-well/Mindwell/angular && npm install && npm install -g grunt-cli)"
script:
    - make secret_passphrase
    - make unit_test
    - coverage combine
    - "(cd mind-well/Mindwell/angular && grunt test)"
after_success:
    coveralls
