language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt"
before_script:
    - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.6.zip
    - unzip google_appengine_1.9.6.zip
script: make unit_test
after_success:
    coveralls
