language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt"
    - "gem install coveralls-lcov"
    - "(cd mind-well/Mindwell/angular && npm install && npm install -g grunt-cli)"
script:
    - make secret_passphrase
    - make unit_test
    - coverage combine
    - "(cd mind-well/Mindwell/angular && grunt test)"
    - "(cd mind-well/Mindwell/angular && coveralls-lcov -v -n coverage/phantomjs/lcov.info > coverage.json)"
after_success:
    coveralls --merge=mind-well/Mindwell/angular/coverage.json
