application: mindwellonline
version: 3-0-0-20150329-3-angular
runtime: python27
api_version: 1
threadsafe: false

default_expiration: "12h"

builtins:
- appstats: on
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: Mindwell/static/images/favicon.ico
  upload: Mindwell/static/images/favicon.ico

- url: /static
  static_dir: Mindwell/static

- url: /angular
  static_dir: Mindwell/angular/dist

#- url: /test.*
#  script: Mindwell/gaeunit/gaeunit.py

- url: /administrator.*
  script: main.app
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /.*
  script: main.app
  login: required
  secure: always

libraries:
- name: django
  version: "1.5"
- name: pycrypto
  version: "2.3"
skip_files:
# app engine defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# mindwell
- ^(.*/)?.*/node_modules/.*$

